version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://lambda-zip-files-cicd/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name lambda-CICD-demo --s3-bucket lambda-zip-files-cicd --s3-key deployment_package.zip \
       --region US East (N. Virginia) us-east-1
      - echo "Deployment complete!" 